name: SuperHubPlugin
main: com.samy.superhub.SuperHubPlugin
version: 1.0
api-version: 1.20
description: Mon premier plugin Minecraft Spigot.
author: Samy

commands:
  spawn:
    display: true
    description: Téléporte le joueur au spawn
    usage: /spawn
